name: Generate Home Page Content

on:
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight UTC
  workflow_dispatch:     # allows manual triggering

jobs:
  generate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run content generation script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: node src/generateHomePageContentRunner.js
